// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABobbarjciP-3Kw6nVPTJqbknvHD7TLi8',
    appId: '1:358876935299:web:0069c8079e7a2253fe17b6',
    messagingSenderId: '358876935299',
    projectId: 'fir-analytics-65d01',
    authDomain: 'fir-analytics-65d01.firebaseapp.com',
    storageBucket: 'fir-analytics-65d01.firebasestorage.app',
    measurementId: 'G-DY8CPRH76S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZZWS9SbmQTL4zCb02S6mUtYhZpbtxYbw',
    appId: '1:358876935299:android:2c22e69f05f777a6fe17b6',
    messagingSenderId: '358876935299',
    projectId: 'fir-analytics-65d01',
    storageBucket: 'fir-analytics-65d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjtYouNLFx2DZ61q7ZNmZUcME4Je4IgU0',
    appId: '1:358876935299:ios:7b441d2be79e5891fe17b6',
    messagingSenderId: '358876935299',
    projectId: 'fir-analytics-65d01',
    storageBucket: 'fir-analytics-65d01.firebasestorage.app',
    iosBundleId: 'com.example.webScrapingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjtYouNLFx2DZ61q7ZNmZUcME4Je4IgU0',
    appId: '1:358876935299:ios:7b441d2be79e5891fe17b6',
    messagingSenderId: '358876935299',
    projectId: 'fir-analytics-65d01',
    storageBucket: 'fir-analytics-65d01.firebasestorage.app',
    iosBundleId: 'com.example.webScrapingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABobbarjciP-3Kw6nVPTJqbknvHD7TLi8',
    appId: '1:358876935299:web:99f5fc6dcc744e66fe17b6',
    messagingSenderId: '358876935299',
    projectId: 'fir-analytics-65d01',
    authDomain: 'fir-analytics-65d01.firebaseapp.com',
    storageBucket: 'fir-analytics-65d01.firebasestorage.app',
    measurementId: 'G-J9PTVVC98R',
  );
}
